### ISSUE TITLE
Epic Story # 1

### ISSUE THREAD

**Issue by Ryoumi** [COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker#25]
As a card game player, I want to have a website that has a working user interface that I can build decks to keep track of my decks, add and delete cards, and enter the number of times I have won and lost with that deck; so that i can get some data on the current deck that i am playing. As someone who likes designs I would like to have the ability to more closely inspect cards in a deck so that I can appreciate the art on each card. As a data enthusiast I would like to know the average win-rate of each card in the game over multiple users so that I can select the best cards to use in my deck.

- [x] Domenic - Add buttons to the home page. Add background to the homepage and deck builder page.

- [x] Kristal - create a csv file that will serve as the statistic for the cards.  3 fields  - card code, number of wins, number of losses. Research connecting a database to a web server. Report at the end of the week

- [x] Alex - Add features to have hover over cards make pictures appear

- [x] Tristan - Add a win loss counter to the deck builder. Get a delete button working for the deck builder.

**Comment by sjiang1** [comment]
Hello! Thank you for submitting your link on Canvas!
Please split this issue into three. Each issue will hold one user story. (Every issue should have its own task list.)
