### ISSUE TITLE
Epic Story #1: User Interface 

### ISSUE THREAD

**Issue by Ryoumi** [COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker#26]
As a card game player, I want to have a website that has a working user interface that I can build decks to keep track of my decks, add and delete cards, and enter the number of times I have won and lost with that deck; so that i can get some data on the current deck that I am playing.

Week of 9/28/20
- [x]  Domenic - Add buttons to the home page. Add background to the homepage and deck builder page.

Week of 10/19/20

- [x] Domenic - Make data input page button for home page. #43 

- [x] Domenic - Make a navigation bar for the other web pages. #43 

- [x] Tristan - Add deck by deck code #42 

Week of 10/26/20

- [x] Tristan - Decrease unnecessary inputs to page #50 

Week of 11/2/20

- [x] Tristan - Condense current deck to show number of copies of each card. #56 

- [x] Domenic - Clean up Data Input Page so that you can add champions one at a time instead of having them there all on load. #58 

Week of 11/9/20

- [x] Domenic - Add navigation bar to the stat viewer page and a button to the stat viewer page get them connected with all the other pages. #65 

- [x] Tristan - Create a feature to export deckcode from deckbuilder. #66

**Comment by sjiang1** [comment]
The user story talks about the following features:

- build decks to keep track of my decks
- add and delete cards
- enter the number of times I have won and lost with that deck
- some data on the current deck that I am playing

The UI is not that important in this user story, but the functionality of the website seems very important to this user. Is my understanding correct?

**Comment by sjiang1** [comment]
Will you add tasks to this epic in the future?

**Comment by tristan-shah** [comment]
Hi Professor,

I think in this story most of the changes seem related to UI except for maybe issue #42. I will probably be adding improvements to deckbuilder page to this.

Thanks,
Tristan
