### ISSUE TITLE
Epic Story # 3: Database and Data Gathering

### ISSUE THREAD

**Issue by Ryoumi** [COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker#28]
As a data enthusiast I would like to know the average win-rate of each card in the game over multiple users so that I can select the best cards to use in my deck.

Week of 9/28/20
- [x]  Kristal - create a csv file that will serve as the statistic for the cards. 3 fields - card code, number of wins, number of losses. Research connecting a database to a web server. Report at the end of the week

- [x]  Tristan - Add a win loss counter to the deck builder. Get a delete button working for the deck builder.

Week of 10/5/20
- [x] Kristal - Start moving our project to an actual database. Issue #31 

- [x] Tristan - Fix delete card so that it deletes only one copy of the card. Issue #30 

- [x] Domenic - Research how to collect data and start gathering data. Issue #29 

Week of 10/19/20
- [x] Kris - Tweaking database features #45
