### ISSUE TITLE
Epic Story #4: Data entry for database

### ISSUE THREAD

**Issue by tristan-shah** [COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker#35]
As a user, I want a way to enter my player information so that I can generate meaningful statistics from it.

---
Week of 11/9/2020
- [x] Create MySql database - Kris #67 

---
Week of 11/2/2020

- [x] Clean up the database - Kris #59 

---
Week of 10/28/2020
- [x] Create a method that adds a user's list of decks to the database (by deck codes) - Kristal #52 

Week of 10/12/2020

- [x] Create initial page and add background. General front end. - Domenic #36
- [x] Create a form with a field for each piece of data: Select deck, Opponent region, Opponent champions, win or loss - Tristan #37 

- [x] Link the input form to the database so it updates a table which stores all of this information - Kristal #38 

- [x] Generate initial statistics (win rate, card usage, etc.) to prepare for displaying them to the user - Alex #39
