### ISSUE TITLE
Epic Story #6: Creating a detailed view of data collected

### ISSUE THREAD

**Issue by acdpsn** [COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker#60]
As a player, I'd like to be able to see what cards and what decks have the best chance of winning.

Week of 10/19/20
 - [x] get some stats from database - Alex #39

Week of 10/26/20
 - [x] create a new page and show stats on it - Alex #51

Week of 11/2/20
 - [x] show more in-depth data on the page #57

Week of 11/9/20
 - [x] analyze data and display trends (does not have to be on page yet) #69

---

Week of 11/16/20
 - [x] catch up on tasks #72

---

Week of 11/23/20
 - [x] display useful trends to user on page
