### ISSUE TITLE
Epic story #7: Bug fixes

### ISSUE THREAD

**Issue by tristan-shah** [COSC481W-2020Fall/cosc481w-581-2020-fall-stattracker#75]
As a user I would like the stattracker product to work well without bugs.
Week of 11/30/2020
- [ ] Kris - Streamline building process - #79 

Week of 11/16/2020

- [x] Fix dropdown menus so that they display the last selected option #73 

- [x] Domenic - Work out some of the bugs and clean up the webpages.  #71 

- [x] Kris - Work on some bugs and add error messages - #74 

- [ ] Tristan - Dont allow cards to be added if they do not exist #77
